### ISSUE TITLE
implausible output stats

### ISSUE THREAD

**Issue by haowenz** [cchauve/lrcstats#5]
Hi,

I used simlord to simulate long reads and then ran lordec to correct errors. After that, I ran lrcstats and got the stats as follows.

> Error Rate      Throughput      Deletions       Insertions      Substitutions
> Corrected - trimmed     0.454805        695023995       94613189        95167872        177086162
> Uncorrected - trimmed   0.680392        724850026       13027472        43408186        492400657
> Corrected - untrimmed   0.456251        698272364       94990272        95625904        179091569
> Uncorrected - untrimmed 0.680832        728366897       13179958        43910123        494599099

Could you tell me what it means and why there are four lines? Besides, the error rates reported by lrcstats are much higher than the true error rates. Do you have any idea why?

Thanks,
Haowen

**Comment by cchauve** [comment]
Dear Haowen

Could you provide us with the exact parameters used with Simlord and lordec and lrcstat in order that we try to reproduce your experiment ?

Due to the fact it is soon going to be the exam period here at SFU it might take us up t 2 weeks to get back to you, but we will do our best.

Cedric Chauve, PhD
Professor, Department of Mathematics, Simon Fraser University
SFU site director, Pacific Institute for the Mathematical Sciences
https://cchauve.github.io/

**Comment by haowenz** [comment]
> simlord  --read-reference ~/data/yeast/S288C_reference_genome_R64-2-1_20150113/S288C_reference_sequence_R64-2-1_20150113.fsa -c 60 ~/data/yeast/pacbio/yeast_pacbio_simulated_x60

> ${LORDEC_CORRECT_INSTALL_PATH} -T 28 -i ${LONG_READ_PATH} -2 ${SHORT_READ_PATH} -o ${LORDEC_OUTPUT_PATH} -k 19 -s 3

> [Experiment Details]
> experiment_name = yeast_lordec
> # Number of threads you'd like to run the aligner with
> threads = 28
> # python style True or False
> trimmed = False
> extended = False
> id_pos = 0
> 
> [Paths]
> # For each path, please don't include the ending / !
> # Directory to store read data
> data = /home/hzhang639/data/results
> clr = /home/hzhang639/yeast/lordec_corrected_pacbio_simulated_x60.fasta
> # Path to the ref-ulr SAM alignment file
> sam = /home/hzhang639/yeast/pacbio/yeast_pacbio_simulated_x60.fastq.sam
> # Path to the reference genome FASTA file
> ref = /home/hzhang639/yeast/S288C_reference_genome_R64-2-1_20150113/S288C_reference_sequence_R64-2-1_20150113.fsa
> 
> [Initialization Commands]
> # List shell commands you would like to perform before alignment
> # Load python 2.7.2
> module load python/2.7
> # Load g++ 5.1.0
> module load gcc/5.3.0
> 
> [PBS Parameters]
> # Enter the PBS Parameters that will appear in the header of the LRCStats job file
> # Do not prepend each line with a # character - this will be interpreted as a comment
> PBS -q swarm
> PBS -m bea
> PBS -j oe
> PBS -o /home/hzhang639/data/results
> PBS -N lrcstats
> PBS -l nodes=1:ppn=28
> PBS -l walltime=72:00:00

Please let me know  if you need other info.

Thanks,
Haowen

**Comment by haowenz** [comment]
@realseanla I have sent you the data via email.

**Comment by realseanla** [comment]
@haowenz Thanks for your input files. Could you send me your LRCstats temporary files?

**Comment by haowenz** [comment]
@realseanla Could you provide me with a list of LRCstats temporary files so that I can extract them and send it to you? Mine were mixed with other files.

**Comment by realseanla** [comment]
Look for the following files:
* `ref-ulr_alignment.maf`
* `sorted.fasta`
* `sorted.sam`
* `intersected.fasta`
* `intersected.sam`
* `yeast_lordec.maf`
* `yeast_lordec.stats`

Before sending them to me, could you compress the files using gzip? Thanks

**Comment by haowenz** [comment]
I didn't find sorted.fasta. The rest of them are attached.

[output.tar.gz](https://github.com/cchauve/lrcstats/files/1894514/output.tar.gz)

Thanks,
Haowen

**Comment by realseanla** [comment]
In the tar file you sent me, it contains the files
* `HALC.corrected.fa`
* `HALC.split.fa`
* `HALC.trim.fa`
Are these the temporary files outputted by LRCstats?

**Comment by haowenz** [comment]
Sorry. I messed it up. I will send them to you later via email.

**Comment by realseanla** [comment]
Thanks for sending them to me. 

I've looked over your SAM alignment file and the uncorrected read error rate as according to LRCstats, and the error rates for the first read don't match up. In the SAM file, the header states that there are around 800 errors, whereas LRCstats says there is more than 6000. I've also looked at the `ref-ulr_alignment.maf` file, and it seems that the reference and uncorrected reads are vastly different.

This could happen if the reference genome file you provided to LRCstats is different from the reference genome file you gave to SimLoRD. I noticed that the reference genome file you provided to SimLoRD is different from the reference genome file provided to LRCstats. 

Perhaps you could try rerunning LRCstats  with the same reference genome as the one you provided to SimLoRD?

P.S. In the LRCstats output file, trimmed statistics correspond to only the corrected portions of the corrected long reads, and the corresponding aligned section in the uncorrected long read. 

For example, suppose we have the alignment:

ref     AAAAAAAA
uLR  AAAGGAAA
cLR  aaaAAaaa

The trimmed statistics only look at the uppercase segments of cLR, in this case AA in cLR, and the corresponding aligned section in the uLR, i.e. GG.
On the other hand, untrimmed statistics look at the entire length of the alignment.

The "Corrected" statistics correspond to the error rates, etc, of the corrected long reads, whereas the "uncorrected" statistics correspond to the error rates, etc, of the uncorrected long reads.

**Comment by realseanla** [comment]
Oh nevermind, I misread your comment; I can see now that the reference genome you provided to SimLoRD is the same as the one provided to LRCstats. You can ignore my above suggestion. I'll do some further investigation and I'll let you know what I discover.

**Comment by realseanla** [comment]
I've compared your uncorrected long reads file and your reference genome, and it doesn't seem like they line up correctly.
For example, the first read (read 0) in `yeast_pacbio_simulated_x60.fastq` indicates that it arises from position 16183 of the reference genome `S288C_reference_sequence_R64-2-1_20150113.fsa`.
However, comparing the first few dozen bases of the long read and the reference at position 16183, we have
```
>ref
AGTGATGTAGTTCACGTGTGTGCCACTGGTAATAATAGAGATAACTATCTCAGTTAAGTTTGAAA...
>read
CAATCAACTCAGAAGCCCATTATTCTACCTCCATCAGCTCCAGTACTTATAGAATTCATTATTTT...
```
As you can see, the two sequences differ greatly.
The header line of the long read indicates that the long read differs from the reference sequence by 8 percent, so it's unlikely the read arose from the reference sequence above. As well, the SAM file indicates that this read is on the same strand as the reference, so this read isn't the reverse complement of the reference.

From all of this, it seems that there is a bug in SimLoRD, or a different reference genome was provided to LRCstats than the one given to SimLoRD.

**Comment by cchauve** [comment]
Hello
From Sean's email, it looks like the bug might be in SimLoRD's alignments. We are trying to confirm this and will get in touch with the SimLoRD authors if needed.
cedric chauve

**Comment by realseanla** [comment]
Hi Haowen, I've investigated further and I noticed that your reference genome contains multiple chromosomes. Both LRCstats and SimLoRD assumes that the reference genome contains a single chromosome, so SimLoRD outputs incorrect SAM alignment files when the reference has multiple sequences. I concatenated all of the chromosomes in your reference genome into a single super-sequence and fed it into the latest version of SimLoRD using the same parameters you used, and the output SAM alignment file is correct, in that the long reads align to the genome with a total of 8% error rate, which is to be expected. 

With that in mind, redoing your experiements with a reference genome containing a single chromosome should give you reasonable statistics from LRCstats, but please do let me know if there are any other errors or if there is anything I can help you with!

**Comment by sean-la** [comment]
Alternatively, I've updated LRCstats to be compatible with reference genomes containing multiple chromosomes, so you can pull the latest version of LRCstats and try that, too.
